### PR TITLE
adjust signer interface to conform with bee crypto.Signer type

### PR DESCRIPTION
**Pull request by acud**

### CODE REVIEW

**Comment by acud** [comment]
@janos `crypto.Signer` in bee has `EthereumAddress()` that returns `common.Address`. I am a bit afraid this won't work since I did a bit of type translation here. Does this mean I'll have to change bee `Signer` to return a byte slice? and this too?

**Comment by acud** [comment]
cc @ralph-pichler

**Comment by ralph-pichler** [comment]
If it returns anything other than `common.Address` it should be `[20]byte` rather than just a  `[]byte`, that way we at least know every value of that type is actually an address.

Anyway, the original PR which introduced this actually had its own type but we switched to `common.Address` (see here: https://github.com/ethersphere/bee/pull/703#discussion_r492042838). One of the reasons was that there were go eth deps in the signer anyway, due to all the tx signing related stuff. One thing to note is also that `common.Address` and `[20]byte` (or `[]byte`) encode to hex differently, I remember having had some problems there when trying to implement the chequebook stuff with a custom type.

**Comment by acud** [comment]
I changed the Signer interface to conform with the bee interface since doing the bee changes right now is too much of an overhead. we will do this on a later iteration

**Pull request merged**
